create table if not exists public.resume_files (
  id bigint generated by default as identity primary key,
  resume_code text not null references public.resumes(code) on update cascade on delete cascade,
  file_format text not null check (file_format in ('docx', 'pdf')),
  storage_path text not null unique,
  original_filename text not null,
  mime_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 8388608),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (resume_code, file_format)
);

alter table public.resume_files enable row level security;

grant select, insert, update, delete on public.resume_files to authenticated;
grant usage, select on sequence public.resume_files_id_seq to authenticated;

drop policy if exists resume_files_admin_all on public.resume_files;
create policy resume_files_admin_all
on public.resume_files
for all
to authenticated
using ((select private.is_app_admin()))
with check ((select private.is_app_admin()));

insert into public.resume_files (resume_code, file_format, storage_path, original_filename, mime_type, file_size)
select
  r.code,
  case when lower(r.original_filename) like '%.pdf' then 'pdf' else 'docx' end,
  r.storage_path,
  r.original_filename,
  case when lower(r.original_filename) like '%.pdf' then 'application/pdf' else 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' end,
  coalesce((o.metadata ->> 'size')::bigint, 1)
from public.resumes r
left join storage.objects o on o.bucket_id = 'resume-files' and o.name = r.storage_path
where r.storage_path is not null and r.original_filename is not null
on conflict (resume_code, file_format) do update set
  storage_path = excluded.storage_path,
  original_filename = excluded.original_filename,
  mime_type = excluded.mime_type,
  file_size = excluded.file_size,
  updated_at = now();

alter table public.app_settings
  add column if not exists discovery_target_role_keywords text[] not null default array[
    'software','application','web','backend','frontend','full stack','mobile','android','ios','java','python','developer','outsystems','power platform','servicenow','uipath','artificial intelligence','ai','machine learning','data engineer','data scientist','research engineer','quality analyst','technology analyst','qa engineer','test automation','security','cyber','soc','vulnerability','penetration test','grc','information security','it support','help desk','service desk','desktop support','technical support','network engineer','database administrator','systems administrator','cloud engineer','devops','site reliability'
  ],
  add column if not exists discovery_excluded_title_keywords text[] not null default array[
    'senior','sr','staff','principal','lead','leader','manager','head','director','vice president','vp','architect','expert'
  ],
  add column if not exists discovery_criteria_suggestion jsonb,
  add column if not exists discovery_criteria_suggestion_status text not null default 'none',
  add column if not exists discovery_criteria_suggestion_source_resume text references public.resumes(code) on update cascade on delete set null,
  add column if not exists discovery_criteria_suggestion_created_at timestamptz,
  add column if not exists discovery_criteria_updated_at timestamptz not null default now();

alter table public.app_settings drop constraint if exists app_settings_discovery_criteria_suggestion_status_check;
alter table public.app_settings add constraint app_settings_discovery_criteria_suggestion_status_check
check (discovery_criteria_suggestion_status in ('none', 'pending', 'approved', 'rejected'));

create index if not exists app_settings_discovery_criteria_suggestion_source_resume_idx
on public.app_settings (discovery_criteria_suggestion_source_resume);

comment on column public.app_settings.discovery_criteria_suggestion is
  'A resume-derived proposal. The scanner continues using active columns until the administrator explicitly approves it.';
