create schema if not exists private;

revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

create table public.app_admins (
  email text primary key check (email = lower(email)),
  user_id uuid unique references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  linked_at timestamptz
);

create table public.private_profile (
  id smallint primary key default 1 check (id = 1),
  full_name text not null,
  preferred_name text not null,
  date_of_birth date not null,
  nationality text not null,
  current_pass text not null,
  pass_expiry date not null,
  available_from date not null,
  languages text[] not null default '{}',
  mandarin_proficiency boolean not null default false,
  singapore_citizen_or_pr boolean not null default false,
  sponsorship_required boolean not null default true,
  location text not null,
  notion_url text,
  updated_at timestamptz not null default now()
);

create table public.resumes (
  code text primary key,
  name text not null,
  fit text not null,
  recommendation text not null,
  tone text not null default 'violet',
  notion_url text,
  sort_order smallint not null default 0,
  updated_at timestamptz not null default now()
);

create table public.jobs (
  id bigint generated by default as identity primary key,
  notion_page_id text unique,
  company text not null,
  position text not null,
  role_track text not null default 'Other',
  match_score integer not null default 0 check (match_score between 0 and 100),
  match_level text not null default 'Review',
  sponsorship text not null default 'Unknown',
  location text not null default 'Singapore',
  work_mode text not null default 'Not specified',
  date_found date,
  matched_skills text[] not null default '{}',
  gaps_risks text,
  pipeline text not null default 'Discovered',
  approved_to_apply boolean not null default false,
  employment_type text,
  source text,
  job_url text,
  career_page text,
  ats_platform text,
  cv_version text,
  cv_status text,
  cover_letter_status text,
  ai_application_policy text,
  salary text,
  saved boolean not null default false,
  notion_url text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index jobs_match_level_idx on public.jobs (match_level);
create index jobs_pipeline_idx on public.jobs (pipeline);
create index jobs_date_found_idx on public.jobs (date_found desc nulls last);

create table public.app_settings (
  id smallint primary key default 1 check (id = 1),
  notion_connected boolean not null default false,
  notion_data_source_id text not null,
  notion_hub_url text not null,
  last_notion_sync timestamptz,
  last_sync_status text not null default 'Not connected',
  last_sync_message text,
  auto_sync_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.app_admins (email)
values ('ledonguyentu@gmail.com');

insert into public.private_profile (
  full_name,
  preferred_name,
  date_of_birth,
  nationality,
  current_pass,
  pass_expiry,
  available_from,
  languages,
  mandarin_proficiency,
  singapore_citizen_or_pr,
  sponsorship_required,
  location,
  notion_url
)
values (
  'Le Do Nguyen Tu',
  'Brian',
  '2005-04-21',
  'Vietnamese',
  'Student''s Pass',
  '2026-09-30',
  '2026-08-31',
  array['Vietnamese', 'English'],
  false,
  false,
  true,
  'Singapore',
  'https://app.notion.com/p/3c0bd4ad42a98152ab5ccc7721fe1c81'
);

insert into public.resumes (code, name, fit, recommendation, tone, notion_url, sort_order)
values
  ('DEV', 'Developer', 'Backend, full-stack, APIs, integrations', 'Recommended for software engineering roles', 'violet', 'https://app.notion.com/p/3c0bd4ad42a98188898bf1d821fe1425', 1),
  ('S+D', 'Security + Development', 'Secure software, AppSec, cloud security', 'Best for hybrid engineering roles', 'cyan', 'https://app.notion.com/p/3c0bd4ad42a98168a2edfc5040d36adb', 2),
  ('SEC', 'Security', 'SOC, vulnerabilities, forensics, governance', 'Best for dedicated security roles', 'green', 'https://app.notion.com/p/3c0bd4ad42a981648125d187a397a7da', 3);

insert into public.jobs (
  company,
  position,
  role_track,
  match_score,
  match_level,
  sponsorship,
  location,
  work_mode,
  date_found,
  matched_skills,
  gaps_risks,
  pipeline,
  source
)
values
  ('Xiaomi', 'Software Engineer, Fresh Graduate', 'Software', 88, 'Strong', 'Unknown', 'Singapore', 'On-site', '2026-08-19', array['Python', 'APIs', 'Backend'], 'Confirm sponsorship and graduate eligibility before preparing the final application.', 'Review', 'Prepared snapshot'),
  ('Talentsis', 'Graduate Cloud Infrastructure Engineer', 'Cloud', 78, 'Review', 'Unknown', 'Singapore', 'Hybrid', '2026-08-19', array['Cloud', 'Infrastructure', 'Security'], 'Verify the employer, salary range, and sponsorship pathway.', 'Review', 'Prepared snapshot'),
  ('Xiaomi', 'Computer Software Engineer, A132810', 'Software', 38, 'Blocked', 'Unknown', 'Singapore', 'On-site', '2026-08-18', array['Software', 'Mandarin required'], 'Blocked because the listing requires Mandarin.', 'Blocked', 'Prepared snapshot'),
  ('Xiaomi', 'Cloud Engineer, Fresh Graduate', 'Cloud', 36, 'Blocked', 'Unknown', 'Singapore', 'On-site', '2026-08-18', array['Cloud', 'Mandarin required'], 'Blocked because Mandarin is mandatory.', 'Blocked', 'Prepared snapshot');

insert into public.app_settings (
  notion_data_source_id,
  notion_hub_url
)
values (
  'e1248229-3597-4222-b9a5-49991972013f',
  'https://app.notion.com/p/cf3a242773ef4ce686fde98a41e8f63f'
);

create or replace function private.is_app_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_admins
    where email = lower(coalesce((select auth.jwt())->>'email', ''))
      and (user_id is null or user_id = (select auth.uid()))
  );
$$;

revoke all on function private.is_app_admin() from public;
grant execute on function private.is_app_admin() to authenticated, service_role;

create or replace function private.link_admin_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.app_admins
  set user_id = new.id,
      linked_at = now()
  where email = lower(new.email)
    and (user_id is null or user_id = new.id);
  return new;
end;
$$;

revoke all on function private.link_admin_user() from public;

create trigger link_admin_user_after_auth_change
after insert or update of email on auth.users
for each row execute function private.link_admin_user();

create or replace function public.is_current_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select private.is_app_admin();
$$;

revoke all on function public.is_current_admin() from public, anon;
grant execute on function public.is_current_admin() to authenticated;

create or replace function public.store_notion_token(token_value text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_id uuid;
begin
  if not private.is_app_admin() then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  if token_value is null or char_length(trim(token_value)) < 20 or char_length(token_value) > 512 then
    raise exception 'Invalid Notion integration token';
  end if;

  select id into existing_id
  from vault.secrets
  where name = 'brian_notion_token'
  limit 1;

  if existing_id is null then
    perform vault.create_secret(trim(token_value), 'brian_notion_token', 'Brian Job Command Center Notion integration');
  else
    perform vault.update_secret(existing_id, trim(token_value), 'brian_notion_token', 'Brian Job Command Center Notion integration');
  end if;

  update public.app_settings
  set notion_connected = true,
      last_sync_status = 'Ready to sync',
      last_sync_message = 'Notion connection saved securely in Supabase Vault.',
      updated_at = now()
  where id = 1;
end;
$$;

revoke all on function public.store_notion_token(text) from public, anon;
grant execute on function public.store_notion_token(text) to authenticated;

create or replace function public.read_notion_token_for_service()
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  token_value text;
begin
  if coalesce((select auth.jwt())->>'role', '') <> 'service_role' then
    raise exception 'Service role required' using errcode = '42501';
  end if;

  select decrypted_secret into token_value
  from vault.decrypted_secrets
  where name = 'brian_notion_token'
  limit 1;

  return token_value;
end;
$$;

revoke all on function public.read_notion_token_for_service() from public, anon, authenticated;
grant execute on function public.read_notion_token_for_service() to service_role;

alter table public.app_admins enable row level security;
alter table public.private_profile enable row level security;
alter table public.resumes enable row level security;
alter table public.jobs enable row level security;
alter table public.app_settings enable row level security;

create policy app_admins_admin_select
on public.app_admins for select
to authenticated
using ((select private.is_app_admin()));

create policy private_profile_admin_all
on public.private_profile for all
to authenticated
using ((select private.is_app_admin()))
with check ((select private.is_app_admin()));

create policy resumes_admin_all
on public.resumes for all
to authenticated
using ((select private.is_app_admin()))
with check ((select private.is_app_admin()));

create policy jobs_admin_all
on public.jobs for all
to authenticated
using ((select private.is_app_admin()))
with check ((select private.is_app_admin()));

create policy app_settings_admin_all
on public.app_settings for all
to authenticated
using ((select private.is_app_admin()))
with check ((select private.is_app_admin()));

revoke all on public.app_admins, public.private_profile, public.resumes, public.jobs, public.app_settings from anon;
grant select on public.app_admins to authenticated;
grant select, insert, update, delete on public.private_profile, public.resumes, public.jobs, public.app_settings to authenticated;
grant usage, select on sequence public.jobs_id_seq to authenticated;

