create extension if not exists supabase_vault;

alter table public.jobs
  add column if not exists job_description text;

alter table public.app_settings
  add column if not exists document_provider text not null default 'gemini',
  add column if not exists document_model text not null default 'gemini-3.6-flash',
  add column if not exists document_endpoint text,
  add column if not exists document_provider_configured boolean not null default false,
  add column if not exists document_provider_updated_at timestamptz;

create table if not exists public.generated_documents (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  document_type text not null check (document_type in ('resume', 'cover_letter')),
  storage_path text not null unique,
  filename text not null,
  source_resume_code text not null references public.resumes(code),
  provider text not null,
  model text not null,
  match_score integer check (match_score between 0 and 100),
  created_at timestamptz not null default now()
);

create index if not exists generated_documents_job_created_idx
on public.generated_documents (job_id, created_at desc);

alter table public.generated_documents enable row level security;

drop policy if exists generated_documents_admin_all on public.generated_documents;
create policy generated_documents_admin_all
on public.generated_documents for all
to authenticated
using ((select private.is_app_admin()))
with check ((select private.is_app_admin()));

revoke all on public.generated_documents from anon;
grant select, insert, update, delete on public.generated_documents to authenticated;
grant usage, select on sequence public.generated_documents_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'generated-documents',
  'generated-documents',
  false,
  10485760,
  array['application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admin can read generated documents" on storage.objects;
create policy "Admin can read generated documents"
on storage.objects for select
to authenticated
using (bucket_id = 'generated-documents' and private.is_app_admin());

drop policy if exists "Admin can upload generated documents" on storage.objects;
create policy "Admin can upload generated documents"
on storage.objects for insert
to authenticated
with check (bucket_id = 'generated-documents' and private.is_app_admin());

drop policy if exists "Admin can update generated documents" on storage.objects;
create policy "Admin can update generated documents"
on storage.objects for update
to authenticated
using (bucket_id = 'generated-documents' and private.is_app_admin())
with check (bucket_id = 'generated-documents' and private.is_app_admin());

drop policy if exists "Admin can delete generated documents" on storage.objects;
create policy "Admin can delete generated documents"
on storage.objects for delete
to authenticated
using (bucket_id = 'generated-documents' and private.is_app_admin());

create or replace function public.store_document_provider_config(
  provider_value text,
  key_value text,
  model_value text,
  endpoint_value text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_provider text := lower(trim(coalesce(provider_value, '')));
  normalized_model text := trim(coalesce(model_value, ''));
  normalized_endpoint text := nullif(trim(coalesce(endpoint_value, '')), '');
  existing_id uuid;
begin
  if not private.is_app_admin() then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  if normalized_provider not in ('gemini', 'openai_compatible') then
    raise exception 'Unsupported document provider';
  end if;

  if char_length(trim(coalesce(key_value, ''))) < 16 or char_length(key_value) > 4096 then
    raise exception 'Enter a valid provider key';
  end if;

  if char_length(normalized_model) < 2 or char_length(normalized_model) > 160 then
    raise exception 'Enter a valid model name';
  end if;

  if normalized_provider = 'openai_compatible' then
    if normalized_endpoint is null or normalized_endpoint !~ '^https://[^[:space:]]+$' then
      raise exception 'A secure HTTPS endpoint is required for an OpenAI-compatible provider';
    end if;
    if char_length(normalized_endpoint) > 1000 then
      raise exception 'Provider endpoint is too long';
    end if;
  else
    normalized_endpoint := null;
  end if;

  select id into existing_id
  from vault.secrets
  where name = 'document_provider_key'
  limit 1;

  if existing_id is null then
    perform vault.create_secret(
      trim(key_value),
      'document_provider_key',
      'Private key for on-demand resume and cover letter generation'
    );
  else
    perform vault.update_secret(
      existing_id,
      trim(key_value),
      'document_provider_key',
      'Private key for on-demand resume and cover letter generation'
    );
  end if;

  update public.app_settings
  set document_provider = normalized_provider,
      document_model = normalized_model,
      document_endpoint = normalized_endpoint,
      document_provider_configured = true,
      document_provider_updated_at = now(),
      updated_at = now()
  where id = 1;
end;
$$;

revoke all on function public.store_document_provider_config(text, text, text, text) from public, anon;
grant execute on function public.store_document_provider_config(text, text, text, text) to authenticated;

create or replace function public.read_document_provider_key_for_service()
returns text
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  key_value text;
begin
  if coalesce((select auth.jwt())->>'role', '') <> 'service_role' then
    raise exception 'Service role required' using errcode = '42501';
  end if;

  select decrypted_secret into key_value
  from vault.decrypted_secrets
  where name = 'document_provider_key'
  limit 1;

  return key_value;
end;
$$;

revoke all on function public.read_document_provider_key_for_service() from public, anon, authenticated;
grant execute on function public.read_document_provider_key_for_service() to service_role;

create or replace function public.clear_document_provider_config()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  existing_id uuid;
begin
  if not private.is_app_admin() then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  select id into existing_id
  from vault.secrets
  where name = 'document_provider_key'
  limit 1;

  if existing_id is not null then
    delete from vault.secrets where id = existing_id;
  end if;

  update public.app_settings
  set document_provider_configured = false,
      document_provider_updated_at = now(),
      updated_at = now()
  where id = 1;
end;
$$;

revoke all on function public.clear_document_provider_config() from public, anon;
grant execute on function public.clear_document_provider_config() to authenticated;
